name: rental_cars
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  google_fonts: ^3.0.1
  date_time_picker: ^2.1.0
  blobs: ^2.0.0
  carousel_slider: ^4.1.1
  carousel_indicator: ^1.0.6
  auto_size_text: ^3.0.0
  razorpay_flutter: ^1.2.3
dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/Images/6867608_28803.jpg
    - assets/Images/wallpaperflare-cropped.jpg
    - assets/Images/istockphoto-1300845620-612x612.jpg
    - assets/Images/alessio-lin--6LYjG0H32E-unsplash.jpg
    - assets/Images/515349.jpg
    - assets/Images/2.jpeg
    - assets/Images/1.jpeg
    - assets/Images/3.jpeg
    - assets/Images/4.jpeg
    - assets/Images/5.jpeg
    - assets/Images/help.jpg